# Generated by Django 2.1.3 on 2018-12-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_auto_20181221_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
