# Generated by Django 2.1.3 on 2018-12-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_project_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='dr_audio',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_bt',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='BT'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_camera',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Camera'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_chipset',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Chipset'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_com_parallel',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Comport Parallel'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_cr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='CardReader'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_finger_printer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='FingerPrinter'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_g_sensor',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='G-sensor'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_iamt',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='iAMT'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_lan',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='LAN'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_others',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='others'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_panel',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Panel'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_serial_io',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Serial IO'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_sgx',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='SGX'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_storage',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Storage'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_usb',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='USB'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_vga',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='VGA'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_wireless',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='WirelessLAN'),
        ),
    ]
